### ISSUE TITLE
Fall 23 Todo

### ISSUE THREAD

**Issue by kshannon** [kshannon-ucsd/cogs8#2]
**@kshannon** 
note! Akshay is gone Oct 7-11 and Oct 17-20
- [x] draft email to students about Thursday meet up sept 28th
- [x] send the email ... i.e. "do the thing"
- [x] need to update class schedule for fall 23
- [x] redo slides for fall 23
- [x] redo class website
- [x] update website variables for class schedule calendar
- [x] set up class discord
- [x] clean up classroom and closet with new equipment etc
- [x] set up classroom seating/chairs ... waiting on Ollie...
- [x] clean up class google drive

**@DILING69** 
- [ ] build extra class robots and test them (partly done after Tuesday meet up)
- [x] Add a black and white photo of yourself to lecture 1 : 01_welcome_onboarding slide 2, you can delete Vineeth's photo
- [x] add that same photo to slide 7, you can keep vineeth's there as well for posterity 
- [x] Work through python code -- after akshay is done creating it from vineeth's code.
- [ ] Create self-help guide docs for setting up and working with robot

**@robotics4good**
- [ ] work with @vchelur97 to clean up and comment code. store code in a non-build folder in this repo `/_code/*` and add comments/instructions in this repo's wiki pages
- [ ] inside of classroom closet, 3 boards need to be drilled so Jiesen can finish building the robots. (needed for week 1 or 2 probably, since we only have 1 robot to share between us for now I believe)
- [ ] inside of the classroom closet I put the pencil pusher activity. we need to rebuild this, ideally a nice version that we can laser print etc and is very durable. (needed for like week 5)

**Course Creations**
- [ ] class spreadsheet for OH sign up (linked on website added in google drive) @robotics4good 
- [ ] Create debug help guide for robot set up, added to S3 linked on website @DILING69 (let's have this done by week 2 end of)
- [x] need new class files and assignments for intro to python stuff and intermediate/embedded python, Vineeth has already put together some of this. @robotics4good @vchelur97 we can work on this next tuesday (26th ish)
- [ ] need to create evaluations for assignments (including intro to python stuff) and for final @kshannon @robotics4good we should also think about research here to show learning outcomes
- [x] need to create sign-in attendance sheet @kshannon 
- [x] need to charge robot batteries

**Comment by kshannon** [comment]
@robotics4good  @DILING69  is this good?
Hello COGS 8 Students,

Welcome to the Fall quarter! For many of you, this is one of your inaugural college courses, which is undoubtedly an exciting journey ahead.

A quick heads-up about our COGS 8 class: It's unique in its format. We meet for a hands-on ~3 hour lecture session every Tuesday. Our first session, however, will be a discussion section scheduled for September 28th (Thursday) due to UCSD's start date. I warmly invite each of you to join us at HSS 1346 (https://youtu.be/FLrMklZEYek or if that does not work "https :// youtu (dot) be/FLrMklZEYek" ) for this initial 50-minute meeting. It'll be a great opportunity to get acquainted with me, your TA (Akshay), and IA (Jiesen). Our official class will start on October 3rd (Tuesday) at 09:30.

Attendance is mandatory for both the Tuesday lectures and Thursday discussion sections, given the hands-on, robotics-centric nature of this course.

To ensure you're well-prepared, please visit our course website where you'll find all the essential information: https://kshannon.github.io/ucsd-cogs8/ 

If the link doesn't work directly (as UCSD sometimes sanitizes URLs in these group emails), here's another version of the URL for your convenience: "https:// kshannon (dot) github (dot) io/ucsd-cogs8/"

I'm looking forward to meeting you this Thursday. If you can't make it, I'll eagerly await our class on the subsequent Tuesday.

Cheers,
Kyle

**Comment by kshannon** [comment]
**LECTURE SLIDES AND DISCUSSION SLIDES**: @robotics4good I am creating a lecture slide for each class lecture, so 10 slides. Some decks will just have a few slides. but for e.g. in week 2 where we are doing python, if we are not putting the python hands on activity in the slides, and are instead opening up a google colab, then I would like to have a slide in there saying, open up file: abc123.ipynb and follow along, so I know which file to open up and also what file students should open up (linked from the website). Essentially the slides for each week should serve as our template for what to do that week. We can also have a slide in there saying "DISCUSSION SECTION" and a few slides after that so you and Jiesen know what to go over. It serves as one resource. also if one of us needs to cover for the other then it makes it easy as well. thoughts?

TODO:
- [x] week 1 - slides are done, we just need to add in vineeth's intro to python stuff and whatever else akshay wants to cover? we can work on this together. @robotics4good @kshannon 
- [x] week 2 - we will need to add the next round of intermediate python tasks to this lecture. should be relatively simple and can take from vineeth's intro stuff @robotics4good @kshannon 
- [ ] week 3 - add embedded python slides/in class work, add more BBC microbit tutorial stuff, taken from website @robotics4good @kshannon 
- [ ] week 4 - add ctm slides and rearrange, move inch worm grand prix to next week, add team formation as well as a slide for grand prix worms @kshannon 
- [ ] week 5 - add slides for project, plus rubric, make sure grand prix worm slide is in here @kshannon 
- [ ] week 6 - make sure these slides are trimmed as much as possible and add a slide about continued to work on embodied/embedded project @kshannon 
- [ ] week 7 -   TODO...
- [ ] week 8 - end slides needs to be updated for the new grading criteria for the final project. @robotics4good @kshannon 
- [ ]  week 9 - place holder slide telling students to continue with their work. perhaps we can have some videos from the previous year cogs 8 final projects for inspiration? @robotics4good
- [ ] week 10 - needs to be completed. basically a good bye message as well as a list of events for the demo day. donuts included? @kshannon
